# Generated by Django 4.0.4 on 2022-05-16 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stockk',
            new_name='stock',
        ),
    ]
